name: Release

on:
  workflow_dispatch:

jobs:
 android:
    runs-on: ubuntu-latest
    env:
      output: "${{ github.workspace }}/build/app/outputs/apk/release"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download OpenList Source Code
        run: |
          cd $GITHUB_WORKSPACE/alist-lib/scripts
          chmod +x *.sh
          ./init_alist.sh
          ./init_web.sh

      - name: Check OpenList Version
        run: |
          cd $GITHUB_WORKSPACE/.github/scripts
          chmod +x ./*.sh
          touch $GITHUB_WORKSPACE/openlist_version
          ./check_openlist.sh
        env:
          VERSION_FILE: ${{ github.workspace }}/openlist_version

      - name: Update OpenList Version and Changelog
        run: |
          if [ ${{ env.openlist_update }} -eq 0 ]
          then
            echo "无更新"
            exit 0
          else
            echo "更新本地 openlist_version ${{ env.openlist_version }}"
            echo -e "[自动同步OpenList] ${{ env.openlist_version }}\n项目已停止维护，推荐使用OpenList官方Flutter应用[OpenListTeam/OpenList-Mobile](https://github.com/OpenListTeam/OpenList-Mobile/)" > $GITHUB_WORKSPACE/CHANGELOG.md
            echo -e "${{ env.openlist_version }}" > $GITHUB_WORKSPACE/openlist_version
          fi

      - uses: actions/setup-go@v5
        with:
          go-version: 1.22
          cache-dependency-path: ${{ github.workspace }}/alist-lib/alist/go.sum

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r25c

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Build OpenList
        run: |
            cd $GITHUB_WORKSPACE/alist-lib/scripts
            chmod +x *.sh
            ./init_gomobile.sh
            ./gobind.sh
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: Upload AAR
        uses: actions/upload-artifact@v4
        with:
          name: "OpenList"
          path: "${{ github.workspace }}/android/app/libs/*.aar"

      - name: Init Signature
        run: |
          touch local.properties
          cd android
          echo ALIAS_NAME='${{ secrets.ALIAS_NAME }}' >> local.properties
          echo ALIAS_PASSWORD='${{ secrets.ALIAS_PASSWORD }}' >> local.properties
          echo KEY_PASSWORD='${{ secrets.KEY_PASSWORD }}' >> local.properties
          echo KEY_PATH='./key.jks' >> local.properties
          # 从Secrets读取无换行符Base64解码, 然后保存到到app/key.jks
          echo ${{ secrets.KEY_STORE }} | base64 --decode > $GITHUB_WORKSPACE/android/app/key.jks

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'
      - run: flutter build apk --split-per-abi --release

      - name: Upload missing_rules.txt
        if: failure() && steps.gradle.outcome != 'success'
        uses: actions/upload-artifact@v4
        with:
          name: "missing_rules"
          path: "${{ github.workspace }}/build/app/outputs/mapping/release/missing_rules.txt"

      - name: Init APP Version Name
        run: |
          echo "ver_name=$(grep -m 1 'versionName' ${{ env.output }}/output-metadata.json | cut -d\" -f4)" >> $GITHUB_ENV


      - name: Upload App To Artifact arm64-v8a
        if: success () || failure ()
        uses: actions/upload-artifact@v4
        with:
          name: "OpenListFlutter-v${{ env.ver_name }}_arm64-v8a"
          path: "${{ env.output }}/*-v8a.apk"

      - name: Upload App To Artifact arm-v7a
        if: success () || failure ()
        uses: actions/upload-artifact@v4
        with:
          name: "OpenListFlutter-v${{ env.ver_name }}_arm-v7a"
          path: "${{ env.output }}/*-v7a.apk"

      - name: Upload App To Artifact x86
        if: success () || failure ()
        uses: actions/upload-artifact@v4
        with:
          name: "OpenListFlutter-v${{ env.ver_name }}_x86_64"
          path: "${{ env.output }}/*64.apk"
